name: Build on Local Machine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    inputs:
      local-folder-path:
        description: 'Path to the local folder for build'
        required: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build locally
        run: |
          cd ${{ D:\Demo\github build }}
          # Add your build commands here
          # Example: make build
