name: Build on Local Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger build on local server
      run: |
        # Add your command to trigger build on your local server
         ssh  192.168.100.86 "cd D:\Demo\calc && ./build_script.sh"
